import { type Question } from '../services/geminiService';

export const biology2016Exam = {
  id: "euee-2016-biology",
  title: "2016 E.C. ESSLCE Biology Examination",
  subject: "Biology",
  grade: "Grade 12",
  timeLimit: 9000, // 150 minutes (2:30 hours)
  questions: [
    {
      id: "bio16-1",
      question: "Gene flow is the movement of genetic material:",
      options: [
        "without altering the allele frequencies.",
        "that drives a population towards perfection.",
        "without affecting the balance of gene pool of a population.",
        "where organisms either join or leave a population."
      ],
      correctAnswerIndex: 3,
      explanation: "Gene flow (gene migration) occurs when individuals migrate into (immigration) or out of (emigration) a population, transferring alleles between gene pools."
    },
    {
      id: "bio16-2",
      question: "Which one of the following options is a constituent of peripheral nervous system?",
      options: [
        "Afferent nerves, brain and automatic motor nerves",
        "Somatic sensory nerves, spinal cord and efferent nerves",
        "Afferent nerves, efferent nerves and somatic motor nerves",
        "Spinal cord, afferent nerves and somatic sensory nerves"
      ],
      correctAnswerIndex: 2,
      explanation: "The Peripheral Nervous System (PNS) comprises sensory (afferent) and motor (efferent) nerves including somatic and autonomic divisions, whereas the brain and spinal cord belong to the Central Nervous System (CNS)."
    },
    {
      id: "bio16-3",
      question: "Which one of the following structures of neurons is correctly paired with its function?",
      options: [
        "Axon - receives signal from muscle",
        "Cell body - maintains structure and supply energy",
        "Dendrites - protects the neuron and insulate it",
        "Myelin sheath - reduces nerve impulse transmission"
      ],
      correctAnswerIndex: 1,
      explanation: "The cell body (soma) contains the nucleus and organelles that produce energy and maintain neuron viability."
    },
    {
      id: "bio16-4",
      question: "Which one of the following statements explains how nerve impulse is occurred? It occurs as a result of:",
      options: [
        "charge difference across the membrane of axon.",
        "the movement of neurotransmitter molecules into myelin sheath.",
        "balanced charge across the membrane of dendrites.",
        "the movement of neurotransmitter molecules out of cell body."
      ],
      correctAnswerIndex: 0,
      explanation: "A nerve impulse (action potential) is generated by rapid changes in electrical charge difference (depolarization and repolarization) across the axonal membrane due to sodium and potassium ion flux."
    },
    {
      id: "bio16-5",
      question: "Which one of the following statements is an acceptable justification of the importance of synapse? Synapse is:",
      options: [
        "the mechanism of protecting the axon from external damage.",
        "a connection between the appendages of consecutive neurons.",
        "a conductor of action potential towards the end of the dendrite.",
        "the facilitator of the reverse flow of neurotransmitter chemical in neurons."
      ],
      correctAnswerIndex: 1,
      explanation: "A synapse is the specialized junction connecting consecutive neurons (axon terminal to dendrite/soma) to ensure unidirectional transmission."
    },
    {
      id: "bio16-6",
      question: "Assume your friend has a blood type that has no antigen on his red blood cells but produces antibodies a and b, loses blood due to a car accident. If blood transfusion is necessary to save his life, your friend can receive blood from someone with:",
      options: [
        "blood type AB.",
        "blood type B.",
        "blood type O.",
        "blood type A."
      ],
      correctAnswerIndex: 2,
      explanation: "A person with no A or B antigens on RBCs and both anti-A and anti-B antibodies in plasma has blood type O. They can only safely receive blood from a type O donor."
    },
    {
      id: "bio16-7",
      question: "The binomial system of naming developed by Linnaeus comprises two names. Which hierarchical groups are used?",
      options: [
        "Order and family",
        "Kingdom and species",
        "Genus and species",
        "Kingdom and phylum"
      ],
      correctAnswerIndex: 2,
      explanation: "Binomial nomenclature assigns each species a two-part scientific name consisting of its Genus (capitalized) and specific epithet / species (lowercase)."
    },
    {
      id: "bio16-8",
      question: "Which one of the following is the feature of kingdom Monera? Its members are:",
      options: [
        "unicellular without separated nucleus.",
        "multicellular with cell walls.",
        "mainly autotrophic and saprophytic.",
        "reproduced by hypha formation."
      ],
      correctAnswerIndex: 0,
      explanation: "Kingdom Monera consists of prokaryotic organisms (bacteria) which are unicellular and lack a membrane-bound nucleus."
    },
    {
      id: "bio16-9",
      question: "Which alternative given below is comprised of harmful groups from the kingdom Monera, Protista and Fungi, respectively?",
      options: [
        "Trypanosoma, Plasmodium falciparum and Haemophilus ducreyi",
        "Candida albicans, Mycobacterium tuberculosis and Trypanosoma",
        "Haemophilus ducreyi, Trypanosoma and Tinea pedis",
        "Trypanosoma, Plasmodium falciparum and Penicillium"
      ],
      correctAnswerIndex: 2,
      explanation: "Haemophilus ducreyi is a bacterium (Monera), Trypanosoma is a protozoan parasite (Protista), and Tinea pedis (athlete's foot) is a pathogenic fungus (Fungi)."
    },
    {
      id: "bio16-10",
      question: "Which one of the following is a feature of Octopi and squid in phylum mollusca? They have:",
      options: [
        "segmented body with head and thorax.",
        "well-developed brain.",
        "lung as a breathing structure.",
        "hard muscular foot with a hard body."
      ],
      correctAnswerIndex: 1,
      explanation: "Cephalopods (octopi and squids) are advanced mollusks possessing complex nervous systems with large, well-developed brains and acute vision."
    },
    {
      id: "bio16-11",
      question: "What mechanism was used by Gregor Mendel to protect the garden peas from self-pollination? He:",
      options: [
        "opened the flower bud before pollen matured.",
        "sterilized the male part of the flower using chemicals.",
        "covered the flower and protects it from pollinating agents.",
        "selected pure dominant traits for breeding."
      ],
      correctAnswerIndex: 0,
      explanation: "Mendel manually emasculated the flowers by removing the immature anthers before pollen ripened to prevent self-fertilization."
    },
    {
      id: "bio16-12",
      question: "Gregor Mendel crossed two pure-breeding traits of pea plants in his experiment and found only one of the traits expressed in the first generation. This shows that the:",
      options: [
        "expressed trait must be determined by the recessive allele.",
        "two traits in the F1 generation were equally expressed.",
        "alleles masked in the F1 generation were lost due to mutation.",
        "expressed trait must be determined by the dominant allele."
      ],
      correctAnswerIndex: 3,
      explanation: "Mendel's Law of Dominance states that when pure dominant and recessive traits are crossed, the dominant allele masks the recessive allele in the F1 hybrid."
    },
    {
      id: "bio16-13",
      question: "Which one of the following statements correctly describes chromosome structure?",
      options: [
        "The pair of chromosomes is heterozygous in nature.",
        "Chromosomes are similar to a gene in structure.",
        "The DNA is wrapped with ribose sugar to form a chromosome.",
        "Chromosomes are made up of histone bounded DNA."
      ],
      correctAnswerIndex: 3,
      explanation: "Eukaryotic chromosomes consist of chromatin, where double-stranded DNA is tightly wound around histone protein octamers to form nucleosomes."
    },
    {
      id: "bio16-14",
      question: "The breeding mechanism that improves the performance of animals or plants using particular traits is:",
      options: [
        "self-breeding.",
        "selective breeding.",
        "test cross.",
        "combination of traits."
      ],
      correctAnswerIndex: 1,
      explanation: "Selective breeding (artificial selection) involves deliberately mating individuals with desirable phenotypic traits."
    },
    {
      id: "bio16-15",
      question: "Which one of the following birth control methods is correctly matched with its function?",
      options: [
        "Hormonal method - prevents follicle development and ovulation",
        "Physical method - reduces the lining of the uterus",
        "Surgical method - avoids early embryo implantation",
        "Natural method - prevent the ovum from reaching to the uterus"
      ],
      correctAnswerIndex: 0,
      explanation: "Hormonal contraceptives (oral pills, implants) supply estrogen/progestin to suppress pituitary FSH and LH, preventing follicle maturation and ovulation."
    },
    {
      id: "bio16-16",
      question: "The ability of carnivores to survive in an ecosystem is dependent on the availability of prey. This can be considered as:",
      options: [
        "abiotic factor.",
        "catastrophic factor.",
        "edaphic factor.",
        "biotic factor."
      ],
      correctAnswerIndex: 3,
      explanation: "Prey organisms are living biological components of the ecosystem, making prey availability a biotic factor."
    },
    {
      id: "bio16-17",
      question: "Which alternative contains organisms that can occupy a standard upright biomass pyramid from the bottom to the top?",
      options: [
        "Grass, Cricket, Chicken and Lizard",
        "Grass, Cricket, Lizard and Chicken",
        "Grass, Chicken, Cricket and Lizard",
        "Grass, Lizard, Cricket and Chicken"
      ],
      correctAnswerIndex: 0,
      explanation: "Trophic levels from base to apex: Primary producer (Grass) -> Primary consumer (Cricket) -> Secondary consumer (Chicken) -> Tertiary consumer (Lizard)."
    },
    {
      id: "bio16-18",
      question: "The two reverse processes that play a significant role in absorbing and releasing carbon dioxide, respectively are:",
      options: [
        "combustion and photosynthesis.",
        "decomposition and respiration.",
        "respiration and assimilation.",
        "photosynthesis and respiration."
      ],
      correctAnswerIndex: 3,
      explanation: "Photosynthesis fixes/absorbs CO2 from the atmosphere into glucose, while cellular respiration metabolizes glucose and releases CO2."
    },
    {
      id: "bio16-19",
      question: "Which one of the following adaptations is important for survival of polar bear in very cold environments? Having:",
      options: [
        "smaller size",
        "blubbers under the skin",
        "fine silky fur",
        "thick wrinkled ears"
      ],
      correctAnswerIndex: 1,
      explanation: "A thick subcutaneous layer of fat (blubber) provides vital thermal insulation in Arctic conditions."
    },
    {
      id: "bio16-20",
      question: "A student concluded that the stage of meiosis on a prepared slide of plant tissue he observed was Anaphase II. What do you think was the reason to come to this conclusion? Observation of:",
      options: [
        "divided centromere and separated sister chromatids",
        "reformed nuclear envelope and reappearance of nucleolus",
        "one chromosome from each homologous pairs at the poles",
        "crossing over between non-sister chromatids of homologous pairs"
      ],
      correctAnswerIndex: 0,
      explanation: "During Anaphase II of meiosis, centromeres split and sister chromatids separate toward opposite spindle poles."
    },
    {
      id: "bio16-21",
      question: "Which one of the following plant species is endemic to Ethiopia?",
      options: [
        "Persica papaya",
        "Aurocaria baramuleta",
        "Eucaliptus globulose",
        "Guizotia abyssinica"
      ],
      correctAnswerIndex: 3,
      explanation: "Guizotia abyssinica (Noug) is an indigenous oilseed crop endemic to the Ethiopian highlands."
    },
    {
      id: "bio16-22",
      question: "Which one of the following national parks of Ethiopia is declared as the world's heritage site and comprises endemic animals like Walia ibex?",
      options: [
        "Yangudi Rassa National Park",
        "Simien Mountain National Park",
        "Rift Valley National Park",
        "Bale Mountain National Park"
      ],
      correctAnswerIndex: 1,
      explanation: "Simien Mountains National Park is a UNESCO World Heritage Site safeguarding the endangered Walia ibex (Capra walie)."
    },
    {
      id: "bio16-23",
      question: "A mother milks her cow every morning and the milk usually forms curd after three days. What is the first step to investigate why this change happens?",
      options: [
        "Take action to prevent the milk from curdling",
        "Read scientific articles about the reason for curdling of milk",
        "Formulate hypothesis about the reason for milk curdling",
        "Ask a question why the milk forms curd"
      ],
      correctAnswerIndex: 3,
      explanation: "In scientific inquiry, the first step following an observation is to ask a specific research question ('Why does the milk form curd?')."
    },
    {
      id: "bio16-24",
      question: "A drug efficacy test was conducted under similar set up on two groups of infected mice (A and B). Group A were the control whereas Group B were experimental group. A student gave a placebo to the control group and the drug to the experimental group. At the end, the experimental group got better. Which one of the following is true about the result?",
      options: [
        "Conclusion cannot be reached.",
        "The drug has an effect.",
        "Placebo has better effect.",
        "The experiment was wrong."
      ],
      correctAnswerIndex: 1,
      explanation: "Since the experimental group receiving the active drug showed significant recovery compared to the placebo control, the data demonstrates that the drug is effective."
    },
    {
      id: "bio16-25",
      question: "Suppose you did an experiment in a biology laboratory and need to report your work to your biology teacher. Which one of the following steps is correct to report the finding?",
      options: [
        "Title -> Procedure -> Result -> Hypothesis -> Prediction -> Evaluation -> Conclusion -> Acknowledgment",
        "Title -> Hypothesis -> Procedure -> Prediction -> Conclusion -> Result -> Evaluation -> Acknowledgment",
        "Title -> Hypothesis -> Prediction -> Procedure -> Result -> Conclusion -> Evaluation -> Acknowledgment",
        "Title -> Prediction -> Procedure -> Hypothesis -> Result -> Conclusion -> Evaluation -> Acknowledgment"
      ],
      correctAnswerIndex: 2,
      explanation: "Standard formal scientific lab reporting order: Title -> Hypothesis -> Prediction -> Procedure/Methods -> Results/Data -> Conclusion -> Evaluation -> Acknowledgments."
    },
    {
      id: "bio16-26",
      question: "Which one of the following statements explains how the allosteric inhibitors affect enzymes activities? By binding to the:",
      options: [
        "substrate and preventing it from binding to the active site",
        "site other than the active site and altering the shape of the active site",
        "active site of an enzyme and blocking the substrate",
        "active site and altering the shape of the enzyme"
      ],
      correctAnswerIndex: 1,
      explanation: "Allosteric (non-competitive) inhibitors bind to an allosteric regulatory site away from the active site, inducing a conformational change that alters active site shape."
    },
    {
      id: "bio16-27",
      question: "Why are enzymes considered special molecules in metabolism? Because:",
      options: [
        "metabolic processes can produce special products in the presence of enzymes.",
        "enzymes facilitate metabolic reactions under controlled physiological conditions.",
        "enzymes are protein molecules that act as a source of energy.",
        "reactions can't totally take place in the absence of enzymes."
      ],
      correctAnswerIndex: 1,
      explanation: "Enzymes act as biological catalysts, lowering activation energy and enabling metabolic reactions to proceed rapidly under mild cellular temperatures and pH."
    },
    {
      id: "bio16-28",
      question: "Which of the following is the most advanced and recent event in the history of cell biology?",
      options: [
        "Discovery of the double-helix structure of DNA",
        "Enovation of the first scanning electron microscope",
        "Description of the Golgi apparatus",
        "Sequencing of the human genome"
      ],
      correctAnswerIndex: 3,
      explanation: "The completion of the Human Genome Project (2003) is the most recent breakthrough among the listed historical milestones."
    },
    {
      id: "bio16-29",
      question: "A student focused a slide of an onion epidermal cell on pre-estimated width of 2 millimeter field of view under a microscope. What will be the width of each individual cell if you count 8 cells that fit to the field of view during your observation?",
      options: [
        "16 millimeter",
        "0.40 millimeter",
        "0.25 millimeter",
        "4 millimeter"
      ],
      correctAnswerIndex: 2,
      explanation: "Cell width = Field of view diameter / Number of cells = 2 mm / 8 cells = 0.25 mm (250 µm)."
    },
    {
      id: "bio16-30",
      question: "Which one of the following statements is correct about the differences between eukaryotic and prokaryotic cells?",
      options: [
        "membrane bound organelles whereas eukaryotic cells don't have it.",
        "small ribosomes whereas eukaryotic cells have large ribosomes.",
        "cell wall whereas eukaryotic cells don't have cell wall.",
        "division of labor whereas eukaryotic cells don't have it."
      ],
      correctAnswerIndex: 1,
      explanation: "Prokaryotic cells have smaller 70S ribosomes, whereas eukaryotic cells possess larger 80S cytosolic ribosomes."
    },
    {
      id: "bio16-31",
      question: "Which biological tool is correctly matched with its function?",
      options: [
        "Petri dishes - to culture microorganisms",
        "Burette - to measure mass of a substance",
        "Centrifuges - to collect insects",
        "Theodolite - to measure the rate of water flow"
      ],
      correctAnswerIndex: 0,
      explanation: "Petri dishes containing agar media are standard tools for culturing and isolating bacterial/fungal colonies."
    },
    {
      id: "bio16-32",
      question: "A student centrifuge a solution containing plant material in order to separate them based on their mass. After 10 minutes of centrifugation some of the components move to the bottom (A), others to the middle layer (B) and the remaining once to the top layer (C). Which alternative shows the mass of the components in decreasing order?",
      options: [
        "C > A > B",
        "A > B > C",
        "B > A > C",
        "A = B = C"
      ],
      correctAnswerIndex: 1,
      explanation: "In differential centrifugation, the densest/heaviest cellular components pellet to the bottom (A) first, followed by intermediate (B), and lightest at the top supernatant (C): A > B > C."
    },
    {
      id: "bio16-33",
      question: "Which one of the following statements shows the future promise of biological sciences?",
      options: [
        "Finding alternative living place for human population",
        "Using stem cells to repair damaged organs and grow new organ",
        "Finding the adaptation mechanism of plant in new condition",
        "Advising the government on how to conserve environment"
      ],
      correctAnswerIndex: 1,
      explanation: "Regenerative medicine using stem cell biology to repair tissues and grow transplantable organs represents a cutting-edge future frontier."
    },
    {
      id: "bio16-34",
      question: "Which one of the following alternatives contains only organic molecules?",
      options: [
        "Glucose, carbon dioxide, glycine and linoleic acid",
        "Methane, calcium carbonate, linoleic acid and glucose",
        "Methane, glycine, linoleic acid and glucose",
        "Linoleic acid, glucose, calcium carbonate and methane"
      ],
      correctAnswerIndex: 2,
      explanation: "Methane (CH4), glycine (amino acid), linoleic acid (fatty acid), and glucose (sugar) are all organic carbon-hydrogen compounds. CO2 and CaCO3 are inorganic."
    },
    {
      id: "bio16-35",
      question: "Which one of the following properties permits insects to freely walk on water? Its high:",
      options: [
        "specific heat capacity",
        "adhesive force",
        "latent heat of vaporization",
        "surface tension"
      ],
      correctAnswerIndex: 3,
      explanation: "High surface tension caused by strong hydrogen bonding between water molecules allows light insects (like water striders) to walk on water."
    },
    {
      id: "bio16-36",
      question: "Which one of the following properties of enzymes shows their catalytic nature?",
      options: [
        "Being non-specific to substrates",
        "Reducing the activation energy",
        "Being altered in a chemical reaction",
        "Changing the nature of the product"
      ],
      correctAnswerIndex: 1,
      explanation: "A catalyst accelerates biochemical reactions by significantly lowering the activation energy barrier without being consumed."
    },
    {
      id: "bio16-37",
      question: "If an enzyme is named as \"EC 3.4.11.1\" in a systematic naming, what does the number \"3\" represents? It represents the:",
      options: [
        "sub-subclass of an enzyme in relation to its protein nature.",
        "ultra-subclass of an enzyme that is related to the place where they act.",
        "sub-class of an enzyme in relation to the source from where it was discovered.",
        "main class of an enzyme which indicates the type of reaction it catalyses."
      ],
      correctAnswerIndex: 3,
      explanation: "In Enzyme Commission (EC) nomenclature, the first digit represents the major enzyme class (1=Oxidoreductases, 2=Transferases, 3=Hydrolases, etc.)."
    },
    {
      id: "bio16-38",
      question: "In the lock-and-key model of enzymatic action, the activation energy is lowered through:",
      options: [
        "provision of alternative pathway for the reaction.",
        "straining of the substrate molecules bound to the active site.",
        "conformational change of substrate molecules.",
        "permanent modification of the active site of the enzyme."
      ],
      correctAnswerIndex: 1,
      explanation: "Substrate binding puts physical strain on chemical bonds within the substrate, weakening them and facilitating reaction progression."
    },
    {
      id: "bio16-39",
      question: "Which one of the following minerals are used as cofactor for the enzyme alcohol dehydrogenase?",
      options: [
        "Cobalt ions",
        "Magnesium ions",
        "Ferrous ions",
        "Zinc ions"
      ],
      correctAnswerIndex: 3,
      explanation: "Alcohol dehydrogenase requires essential zinc ions (Zn2+) as an inorganic catalytic cofactor."
    },
    {
      id: "bio16-40",
      question: "A student made an experiment to observe the effect of temperature on catalase of mashed potato. At 10°C the mean rate was 0.69 cm/sec, at 20°C was 2.36 cm/sec, at 30°C was 6.6 cm/sec, at 45°C was 2.75 cm/sec, at 50°C was 0.5 cm/sec, at 55°C was 0.27 cm/sec. At which temperature was the reaction fastest?",
      options: [
        "10°C",
        "30°C",
        "50°C",
        "55°C"
      ],
      correctAnswerIndex: 1,
      explanation: "The fastest rate of reaction (6.6 cm/sec) occurred at 30°C, which represents the optimum temperature."
    },
    {
      id: "bio16-41",
      question: "Which one of the following organic molecules has ester bonds in its molecular structure?",
      options: [
        "Triglyceride",
        "Glycogen",
        "Amino acid",
        "Cellulose"
      ],
      correctAnswerIndex: 0,
      explanation: "Triglycerides are lipids formed by esterification of one glycerol molecule with three fatty acids, producing three ester bonds."
    },
    {
      id: "bio16-42",
      question: "Which one of the following statement is correct about the structural organization of hemoglobin? It is formed:",
      options: [
        "when a polypeptide chain folds itself during protein synthesis.",
        "through the association of two or more polypeptide chains.",
        "through folding of secondary structure of a polypeptide chain.",
        "by hydrogen bonding between quaternary and tertiary structures."
      ],
      correctAnswerIndex: 1,
      explanation: "Hemoglobin exhibits quaternary structure formed by the assembly of four separate polypeptide subunits (two alpha and two beta chains)."
    },
    {
      id: "bio16-43",
      question: "The presence of large amount of lipid reduces the density of an animal. Which function of triglycerides is related to this fact?",
      options: [
        "Thermal insulation",
        "Buoyancy",
        "Waterproofing",
        "Respiratory substrate"
      ],
      correctAnswerIndex: 1,
      explanation: "Because lipids have a lower specific gravity/density than water, adipose tissue provides buoyancy to aquatic organisms (like whales and seals)."
    },
    {
      id: "bio16-44",
      question: "The missing number represented by the letter \"n\" in the formula of maltose (C12HnO11) is:",
      options: [
        "12",
        "11",
        "24",
        "22"
      ],
      correctAnswerIndex: 3,
      explanation: "Maltose is a disaccharide formed by condensation of two glucose molecules (2 x C6H12O6 - H2O = C12H22O11), so n = 22."
    },
    {
      id: "bio16-45",
      question: "According to biological scenario, structure is related to function, which one of the following is correctly described?",
      options: [
        "Trachea - millions of air sacs for diffusion of O2 and CO2",
        "Alveoli - supported by cartilage for swallowing food",
        "Nasal passage - large surface area with hairs for filtration of air",
        "Larynx - hair like strictures for mucus production"
      ],
      correctAnswerIndex: 2,
      explanation: "The nasal cavity is lined with ciliated epithelium, vascular mucous membranes, and nasal hairs that trap particles and warm/filter inhaled air."
    },
    {
      id: "bio16-46",
      question: "As compared to the exhaled air, the inhaled air contains:",
      options: [
        "70% oxygen, 0.03% carbon dioxide and 30% nitrogen.",
        "16% oxygen, 4% carbon dioxide and 80% nitrogen.",
        "80% oxygen, 20% carbon dioxide and 0.04% nitrogen.",
        "21% oxygen, 0.04% carbon dioxide and 80% nitrogen."
      ],
      correctAnswerIndex: 3,
      explanation: "Atmospheric inhaled air contains approximately 21% Oxygen, 0.04% Carbon dioxide, and ~78-80% Nitrogen."
    },
    {
      id: "bio16-47",
      question: "A student conducted food tests on 3 samples: Sample 1 turned blue with Benedict's, colourless with ethanol, and mauve with Biuret's. Sample 2 turned red with Benedict's, colourless with ethanol, and mauve with Biuret's. Sample 3 turned yellow with Benedict's, colourless with ethanol, and mauve with Biuret's. What do you conclude?",
      options: [
        "Lipids and reducing sugars are absent from all the three food samples tested.",
        "Proteins and reducing sugars are found in all the food samples at equal concentrations.",
        "Non-reducing sugars are present in all the food samples at different concentrations.",
        "Reducing sugars are found in two of the samples and proteins are found in all the samples."
      ],
      correctAnswerIndex: 3,
      explanation: "Samples 2 and 3 showed positive Benedict's test (red and yellow precipitate = reducing sugars), while all 3 samples showed positive Biuret's test (mauve/purple = proteins)."
    },
    {
      id: "bio16-48",
      question: "What is the scientific reason behind the preference of high altitude areas for training by the Ethiopian Athletes? Because:",
      options: [
        "the RBCs produced are more efficient than those at low altitude.",
        "it helps them to adapt to the high atmospheric pressure of mountains.",
        "the oxygen density is higher than the low altitude.",
        "it helps them to increase their lung capacities."
      ],
      correctAnswerIndex: 0,
      explanation: "Hypoxic high-altitude conditions trigger erythropoietin (EPO) release, increasing total red blood cell mass and oxygen delivery efficiency."
    },
    {
      id: "bio16-49",
      question: "How does oxygen is transported in the human body? It is transported:",
      options: [
        "by simple diffusion along concentration gradient from the lungs to the heart.",
        "from the red blood cells to actively respiring tissues by facilitated diffusion.",
        "from the lungs to actively respiring tissue by hemoglobin of RBC.",
        "by the blood plasma from lower concentration to higher concentration."
      ],
      correctAnswerIndex: 2,
      explanation: "Over 98% of oxygen in human blood binds reversibly to hemoglobin inside erythrocytes forming oxyhemoglobin to be transported to tissues."
    },
    {
      id: "bio16-50",
      question: "Which one of the following statements is well justified why the left ventricle is tough in nature? Because it:",
      options: [
        "forces oxygenated blood out of the heart.",
        "returns deoxygenated blood to the heart.",
        "returns oxygenated blood to the heart.",
        "forces deoxygenated blood out of the heart."
      ],
      correctAnswerIndex: 0,
      explanation: "The left ventricle has thick, muscular walls to generate high systolic pressure required to pump oxygenated blood through the aorta to the systemic circulation."
    },
    {
      id: "bio16-51",
      question: "Which one of the following statements is true about female genital mutilation? It:",
      options: [
        "gives acceptance for marriage.",
        "helps to deliver baby easily.",
        "imposes risk of infection.",
        "keeps girls pure and honest."
      ],
      correctAnswerIndex: 2,
      explanation: "FGM is a harmful traditional practice carrying severe medical risks including hemorrhage, severe infection, tetanus, and birth complications."
    },
    {
      id: "bio16-52",
      question: "Assume that you have a friend who is HIV positive and you are familiar about the case. How can you support your friend if she is injured and needs your help?",
      options: [
        "Help your friend with precautions",
        "Ignore your friend because of the virus",
        "Call to other people to protect you from the virus",
        "Help your friend without any fear of the virus"
      ],
      correctAnswerIndex: 0,
      explanation: "Providing first aid to an injured person requires universal health precautions (wearing sterile gloves and preventing direct blood contact) to ensure mutual safety."
    },
    {
      id: "bio16-53",
      question: "Why are root hairs efficient in uptake of water from the soil? Because they:",
      options: [
        "anchor the plant to the ground.",
        "show positive hydrotropism.",
        "keep turgidity of the cell.",
        "have high surface area to volume ratio."
      ],
      correctAnswerIndex: 3,
      explanation: "Long, thin root hair extensions dramatically maximize the surface area-to-volume ratio for rapid osmosis and mineral absorption."
    },
    {
      id: "bio16-54",
      question: "What will happen to a plant if the apical dominance is removed through repeated pruning? The:",
      options: [
        "plant shades its leaves to withstand the condition.",
        "plant elongates and bends to one direction.",
        "side shoots grow quickly and the plant becomes bushy.",
        "growth of the lateral shoots will be inhibited."
      ],
      correctAnswerIndex: 2,
      explanation: "Removing the shoot apical bud removes the source of auxin, releasing lateral axillary buds from apical dominance and producing a bushy plant."
    },
    {
      id: "bio16-55",
      question: "A farmer sowed cotton seeds in a farm land which fulfills the optimum conditions for germination. After a few days, he observed the newly growing seedlings. Which of the following statements is correct about the farmer's observation? The:",
      options: [
        "growth of plumule above the soil surface",
        "remaining of the cotyledon below the ground",
        "hypogeal germination of the hypocotyl",
        "growth of plumule without forming a hook"
      ],
      correctAnswerIndex: 0,
      explanation: "During epigeal germination (as in cotton), the hypocotyl elongates and pulls the cotyledons and embryonic plumule above the soil surface."
    },
    {
      id: "bio16-56",
      question: "Which one of the following is the main function of Bowman's capsule of the human kidneys?",
      options: [
        "Mineral reabsorption",
        "Prevent back flow of urine",
        "Ultrafiltration of blood",
        "Water preservation"
      ],
      correctAnswerIndex: 2,
      explanation: "Bowman's capsule surrounds the glomerulus and carries out ultrafiltration of blood under hydrostatic pressure, collecting glomerular filtrate."
    },
    {
      id: "bio16-57",
      question: "What is the justification for feeling warm while sweating a lot in a very humid condition?",
      options: [
        "The lower rate of evaporation of water from the skin surfaces",
        "Closure of the glands in the epidermal layer of the skin",
        "An increase in metabolic rate as temperature increases",
        "Unequal distribution of ions on membrane of cells"
      ],
      correctAnswerIndex: 0,
      explanation: "High atmospheric humidity reduces the water vapor concentration gradient, drastically slowing sweat evaporation and evaporative cooling."
    },
    {
      id: "bio16-58",
      question: "As a result of human activities, huge amount of carbon dioxide has been accumulated in the atmosphere. What is the consequence of this phenomenon?",
      options: [
        "Drop in temperature of the earth and death of aquatic organisms",
        "Increased rate of uptake of carbon dioxide by green plants",
        "Preventing certain amount of heat escaping back to the space",
        "Reduction in the sea level and death of aquatic animals"
      ],
      correctAnswerIndex: 2,
      explanation: "CO2 is a greenhouse gas that traps outgoing infrared radiation, preventing heat dissipation into space and causing global warming."
    },
    {
      id: "bio16-59",
      question: "Among the following statements, one briefly describes the concept of climate change. It is the:",
      options: [
        "sudden change in an average rain fall of a limited area.",
        "radical change of local weather condition that sustain for less than a year.",
        "gradual change of atmospheric temperature over a short period of time.",
        "global change in the temperature, precipitation and wind conditions."
      ],
      correctAnswerIndex: 3,
      explanation: "Climate change refers to long-term broad shifts in planetary temperatures, precipitation patterns, and weather systems across decades."
    },
    {
      id: "bio16-60",
      question: "What was the main objective of the United Nations Framework Convention on Climate Change (UNFCCC)?",
      options: [
        "Reduction of the monopole utilization of border crossing rivers to prevent climate change",
        "Prevention of dangerous man-made interference with the climate system",
        "Donation of high carbon projects related to climate change by the developed countries",
        "Prohibition of developing countries from setting up big industries that could affect the climate"
      ],
      correctAnswerIndex: 1,
      explanation: "The ultimate objective of the UNFCCC is to stabilize greenhouse gas concentrations to prevent dangerous anthropogenic interference with the climate system."
    },
    {
      id: "bio16-61",
      question: "Which one of the following research activities has been conducted at Armauer Hansen Research Institute?",
      options: [
        "Improving crop production through genetic engineering",
        "Conserving the genes of endemic plants and animals",
        "Assessing the nutritional status of mothers and babies",
        "Developing drugs for leishmaniasis and tuberculosis"
      ],
      correctAnswerIndex: 3,
      explanation: "The Armauer Hansen Research Institute (AHRI) in Addis Ababa is a renowned biomedical research center specializing in tuberculosis, leprosy, and leishmaniasis."
    },
    {
      id: "bio16-62",
      question: "Which one of the following alternatives contains only protein rich cereals/legumes?",
      options: [
        "Red kidney peas, maize and white pea",
        "White kidney peas, red kidney peas and chickpea",
        "Barley, chickpea and groundnut",
        "Wheat, red kidney peas and sesame"
      ],
      correctAnswerIndex: 1,
      explanation: "Legumes (white kidney beans, red kidney beans, chickpeas) are renowned for their high protein content compared to starchy cereals."
    },
    {
      id: "bio16-63",
      question: "Which one of the following statements is correct about the process of digestion in the stomach?",
      options: [
        "Pepsin hydrolyzes protein molecules into amino acids.",
        "Lipase hydrolyzes fat molecules into fatty acids and glycerol.",
        "Amylase hydrolyzes starch molecules into maltose.",
        "Bile hydrolyzes bigger fat molecules into smaller droplets."
      ],
      correctAnswerIndex: 0,
      explanation: "In the acidic gastric juice, pepsin cleaves peptide bonds in proteins into smaller peptide chains."
    },
    {
      id: "bio16-64",
      question: "Which one of the following statements is correct about the role of trypsin in digestion? It acts on:",
      options: [
        "lipids in the small intestine.",
        "maltose in the mouth.",
        "starch in the stomach.",
        "protein in the small intestine."
      ],
      correctAnswerIndex: 3,
      explanation: "Trypsin is a pancreatic protease secreted into the duodenum that digests polypeptides into peptides in the small intestine."
    },
    {
      id: "bio16-65",
      question: "Which one of the following descriptions about absorption of nutrients in the digestive system is correct?",
      options: [
        "Glycerol molecules are first absorbed into the hepatic portal vein and then to lacteal.",
        "Amino acid molecules are directly absorbed from small intestine into the blood.",
        "Glucose molecules are first absorbed into the lacteal and then enter into the blood.",
        "Fatty acids molecules are absorbed from small intestine directly into the blood."
      ],
      correctAnswerIndex: 1,
      explanation: "Water-soluble nutrients (monosaccharides and amino acids) are absorbed directly into the capillary blood network of the villi, while lipid droplets enter the lacteals."
    },
    {
      id: "bio16-66",
      question: "What is the main function of the dermis of the skin?",
      options: [
        "Production of skin pigments",
        "Prevention of the entry of pathogens",
        "Synthesis of hair and nail proteins",
        "Temperature regulation in homeostasis"
      ],
      correctAnswerIndex: 3,
      explanation: "The dermis contains sweat glands, arterioles (vasodilation/vasoconstriction), and sensory receptors essential for thermoregulation in homeostasis."
    },
    {
      id: "bio16-67",
      question: "In the structure of the human eye, the colored muscular diaphragm that controls the size of the pupil is the:",
      options: [
        "ciliary muscle.",
        "iris.",
        "optic nerve.",
        "pupil."
      ],
      correctAnswerIndex: 1,
      explanation: "The iris is the colored annular diaphragm of smooth muscle regulating light entry into the eye by constricting or dilating the pupil."
    },
    {
      id: "bio16-68",
      question: "A man observed elementary school students spinning around, and realized that none of them could properly walk upright after sudden interruption of the spinning. Which one of the following is the correct reason for this condition?",
      options: [
        "The fluid in the semi circular canal stopped immediately when the body stopped spinning.",
        "The sensory cells were unable to detect stimulus after the spinning was quitted.",
        "The fluid in the semicircular canal kept moving after the spinning was interrupted.",
        "The nerve impulse was transmitted after the spinning was stopped."
      ],
      correctAnswerIndex: 2,
      explanation: "Due to inertia, endolymph fluid in the semicircular canals continues to circulate after spinning stops, sending conflicting motion signals to the brain and inducing dizziness."
    },
    {
      id: "bio16-69",
      question: "Which of the following is the correct description of hormones? They are chemical messengers that:",
      options: [
        "transmit message faster than the nerve system.",
        "regulates many physiological process.",
        "targets only the site of secretion.",
        "are produced in glands that contain ducts."
      ],
      correctAnswerIndex: 1,
      explanation: "Hormones are biochemical regulatory messengers secreted by endocrine (ductless) glands into the bloodstream to coordinate broad physiological processes."
    },
    {
      id: "bio16-70",
      question: "Homeostasis is a mechanism of:",
      options: [
        "keeping internal body environment constant.",
        "adjusting the environment relative to body condition.",
        "keeping external environment stable.",
        "protecting the body from pathogens."
      ],
      correctAnswerIndex: 0,
      explanation: "Homeostasis is the physiological maintenance of a dynamic, stable internal environment (temperature, pH, blood glucose, osmolarity)."
    },
    {
      id: "bio16-71",
      question: "Which one of the following arrangement of molecules in the fluid mosaic model of the cell membrane is correct?",
      options: [
        "Phospholipids fill the protein like a sandwich to retain its rigidity.",
        "Phospholipid molecules are peripherally attached to proteins.",
        "Phospholipids are inserted into the bilayer of protein molecules.",
        "Protein molecules are studded between the phospholipid bilayers."
      ],
      correctAnswerIndex: 3,
      explanation: "The fluid mosaic model describes a viscous phospholipid bilayer with embedded (integral) and surface (peripheral) protein molecules."
    },
    {
      id: "bio16-72",
      question: "What is the role of cholesterol in the cell membrane? It:",
      options: [
        "anchors integral proteins to the cytoskeleton.",
        "reduce the fluidity of the cell membrane at high temperature.",
        "acts as receptor site for hormones and other signaling molecules.",
        "transports hydrophilic molecules into the cell."
      ],
      correctAnswerIndex: 1,
      explanation: "Cholesterol acts as a membrane bidirectional fluidity buffer: restraining phospholipid movement at high temperatures and preventing tight packing at low temperatures."
    },
    {
      id: "bio16-73",
      question: "Regarding cellular organelles: Ribosomes are the site of protein synthesis (1); Golgi body modifies and distributes molecules (2); Mitochondria is the site of aerobic respiration (3); Lysosomes digest foreign cells (4). Which pair correctly represents these functions?",
      options: [
        "2 and 4",
        "2 and 3",
        "1 and 4",
        "1 and 3"
      ],
      correctAnswerIndex: 1,
      explanation: "Mitochondria produce ATP via aerobic cellular respiration, and Golgi apparatus packages and distributes macromolecules."
    },
    {
      id: "bio16-74",
      question: "Potato slices of equal weight were immersed in four different concentrations of salt solutions (1.5, 1.0, 0.5, and 0.1 molars). After a day, the potato slices were reweighted. Which potato slice weights the least?",
      options: [
        "0.1 molars",
        "1.5 molars",
        "0.5 molars",
        "1.0 molars"
      ],
      correctAnswerIndex: 1,
      explanation: "The 1.5 M solution is the most hypertonic, causing the greatest osmotic loss of water from potato tissue and resulting in the lowest final mass."
    },
    {
      id: "bio16-75",
      question: "Suppose you took a container and divided it into two halves by a membrane which is permeable to water and labeled the two halves as \"A\" and \"B\". Finally, you added hypertonic solution in \"A\" and hypotonic solution in \"B\". What will be the expected result of this experiment? The water level of:",
      options: [
        "\"A\" remains constant.",
        "\"B\" decreases.",
        "both \"A\" and \"B\" rise up.",
        "\"B\" rises up."
      ],
      correctAnswerIndex: 1,
      explanation: "Water moves by osmosis from the hypotonic side (B) to the hypertonic side (A), causing the water volume/level in chamber B to decrease."
    },
    {
      id: "bio16-76",
      question: "During oxidative phosphorylation, ATP is produced by combining ADP and inorganic phosphate using energy released from:",
      options: [
        "transport of electrons from complex IV to complex I.",
        "dehydrogenation of pyruvate to acetyl CoA.",
        "decarboxylation of citrate to oxaloacetate.",
        "transfer of electrons from NADH/FADH2 to O2."
      ],
      correctAnswerIndex: 3,
      explanation: "The electron transport chain transfers high-energy electrons from NADH and FADH2 down redox carriers to molecular oxygen (O2), driving ATP synthase."
    },
    {
      id: "bio16-77",
      question: "In a fox population, foxes with thicker fur survived better in cold climate compared to those with thinner fur; however, foxes with thinner fur survived better when the climate was very hot. What type of natural selection is described in this scenario?",
      options: [
        "Diversifying selection",
        "Stabilizing selection",
        "Disruptive selection",
        "Directional selection"
      ],
      correctAnswerIndex: 3,
      explanation: "When environmental shifts favor one extreme phenotype over another depending on climatic direction, it represents directional selection."
    },
    {
      id: "bio16-78",
      question: "Which one of the following comparisons between substrate level and oxidative phosphorylation is correct?",
      options: [
        "34 ATP molecules are produced, but in oxidative phosphorylation 4 ATP molecules are produced per glucose molecule.",
        "ATP is made in the cytosol and matrix, but in oxidative phosphorylation it is made on the inner membrane of mitochondria.",
        "protons are pumped into the inter-membrane space, but in oxidative phosphorylation they are pumped into the cytosol.",
        "oxygen is the final electron acceptor, but in oxidative phosphorylation NAD is the electron acceptor."
      ],
      correctAnswerIndex: 1,
      explanation: "Substrate-level phosphorylation occurs directly in the cytosol (glycolysis) and mitochondrial matrix (Krebs cycle), whereas oxidative phosphorylation occurs on the mitochondrial inner membrane cristae."
    },
    {
      id: "bio16-79",
      question: "Which one of the following determines the cause and effect of lactate production during physical exercise? The demand for:",
      options: [
        "a substrate that can easily release energy leads to production of lactate which results in muscle fatigue.",
        "an easily absorbable molecule leads to the production of lactate that results in muscle fatigue.",
        "lower pH in muscle tissues leads to fermentation of respiratory substrates leading to muscle fatigue.",
        "more energy causes muscle cells to ferment respiratory substrates leading to muscle fatigue."
      ],
      correctAnswerIndex: 3,
      explanation: "High ATP demand exceeding aerobic oxygen supply forces skeletal muscle into anaerobic glycolysis, producing lactic acid and contributing to muscle fatigue."
    },
    {
      id: "bio16-80",
      question: "The view of biochemical origin of life hypothesized that the first life-forms appeared in warm primitive ocean and were heterotrophic. Which one of the following statements can support this idea?",
      options: [
        "Life is the inherent property of the universe which permits unlimited existence through usage of resource in it.",
        "The appearance of dust of unknown source with microbial spores that can feed on organic molecules.",
        "The formation of abundant organic molecules due to radiations and the absence of oxygen led to the primitive living organisms.",
        "Resistant spores from meteorites reached to the earth and used organic molecules to survive in the environment."
      ],
      correctAnswerIndex: 2,
      explanation: "The Oparin-Haldane hypothesis states that abiotic synthesis in a reducing prebiotic atmosphere generated rich organic soup in oceans that gave rise to primordial heterotrophs."
    },
    {
      id: "bio16-81",
      question: "Which statement shows the correct comparison between the Lamarck's and Darwin's theory of evolution?",
      options: [
        "Lamarck believed in the development of new traits due to variation while Darwin believed in their occurrence due to use and disuse of organs.",
        "Darwin recognized the origin of species was through mutation while Lamarck believed it was through effect of the environment.",
        "Lamarck believed the gradual occurrence of changes while Darwin believed in the immediate change of species.",
        "Darwin claimed that variation is heritable while Lamarck considers variation as acquired traits."
      ],
      correctAnswerIndex: 3,
      explanation: "Lamarck proposed inheritance of acquired physical characteristics from use/disuse, whereas Darwin proved natural selection acts upon existing inheritable genetic variations."
    },
    {
      id: "bio16-82",
      question: "Which of the following is true concerning the evidences of evolution?",
      options: [
        "Organisms which have little genetic relationship show similar behavior.",
        "Organisms which live in the same area have similar evolutionary history.",
        "Species that are closely related share the most similar DNA sequences.",
        "Species that live in the same geographic area have the same genetic makeup."
      ],
      correctAnswerIndex: 2,
      explanation: "Molecular biology demonstrates that closely related evolutionary lineages exhibit high degrees of DNA sequence homology and amino acid alignment."
    },
    {
      id: "bio16-83",
      question: "In human evolution brain size increased over the courses of evolution. Which alternative contains hominids arranged in an increasing order of brain size?",
      options: [
        "Homo neandertalensis -> Homo erectus -> Homo habilis -> Homo sapiens",
        "Homo erectus -> Homo habilis -> Homo neandertalensis -> Homo sapiens",
        "Homo erectus -> Homo neandertalensis -> Homo habilis -> Homo sapiens",
        "Homo habilis -> Homo erectus -> Homo neandertalensis -> Homo sapiens"
      ],
      correctAnswerIndex: 3,
      explanation: "Cranial capacity progressive expansion: Homo habilis (~650 cc) -> Homo erectus (~900-1100 cc) -> Homo neanderthalensis (~1450 cc) -> Homo sapiens (~1400 cc modern encephalization)."
    },
    {
      id: "bio16-84",
      question: "The type of gene mutation that results in the change of a triplet (GAG) in a normal hemoglobin to another triplet (GTG) in sickle-cell hemoglobin is:",
      options: [
        "deletion mutation.",
        "insertion mutation.",
        "substitution mutation.",
        "non-disjunction."
      ],
      correctAnswerIndex: 2,
      explanation: "Sickle-cell anemia is caused by a single base-pair substitution (point mutation) replacing adenine with thymine in the beta-globin gene (GAG to GTG)."
    },
    {
      id: "bio16-85",
      question: "Which one of the following statements correctly explains the genetic drift? It is a change in allele frequency due to:",
      options: [
        "independent assortment of chromosomes.",
        "non-random mating of individuals in a population.",
        "chance based sampling error.",
        "relocation of species into other areas."
      ],
      correctAnswerIndex: 2,
      explanation: "Genetic drift represents random fluctuations in allele frequencies from generation to generation due to chance sampling error, especially in small populations."
    },
    {
      id: "bio16-86",
      question: "Identify the correct mechanism of bacterial reproduction by conjugation.",
      options: [
        "Mitotic spindles are produced to separate bacterial DNA into two equal parts.",
        "The recipient bacteria use their pili to pull the donor bacteria during plasmid transfer.",
        "Bacteria take up genetic materials of dead organisms and integrate into their DNA.",
        "A pair of bacteria come together and exchanges their plasmids."
      ],
      correctAnswerIndex: 3,
      explanation: "Bacterial conjugation is horizontal gene transfer where donor and recipient bacteria form a mating bridge (sex pilus) to transfer plasmid DNA."
    },
    {
      id: "bio16-87",
      question: "Which one of the following features is NOT the characteristic feature of fungi? They:",
      options: [
        "have haploid nuclei and multinucleate hypha.",
        "reproduce asexually through spore production.",
        "are either autotrophic, parasitic or saprophytic.",
        "exhibit apical growth of networked hypha."
      ],
      correctAnswerIndex: 2,
      explanation: "Fungi are strictly heterotrophic (saprophytes or parasites) and lack chlorophyll; they are never autotrophic."
    },
    {
      id: "bio16-88",
      question: "What is the argument behind the need of appropriate host cell for viruses to replicate themselves? Because viruses:",
      options: [
        "are obligate saprophyte that can only replicate inside a cell.",
        "have cell surface antigen specific to a given cell type.",
        "lack metabolic capacity to produce energy outside cells.",
        "lack of double strand DNA to duplicate themselves."
      ],
      correctAnswerIndex: 2,
      explanation: "Viruses are obligate intracellular parasites that lack metabolic machinery, ribosomes, and ATP synthesis, relying entirely on the host cell's enzymes for replication."
    },
    {
      id: "bio16-89",
      question: "Which one of the following diseases and their mode of transmission is correctly matched?",
      options: [
        "Salmonellosis - contaminated food",
        "Candidiasis - droplet infection",
        "Chicken pox - fecal-oral-route",
        "Common cold - direct contact"
      ],
      correctAnswerIndex: 0,
      explanation: "Salmonellosis is a foodborne gastrointestinal infection transmitted through contaminated poultry, eggs, water, and uncooked meats."
    },
    {
      id: "bio16-90",
      question: "What is the basic difference between anabolism and catabolism?",
      options: [
        "Anabolism is related to respiration while catabolism is to photosynthesis.",
        "Catabolism is condensation while anabolism is hydrolysis reaction.",
        "Anabolism is energy absorbing while catabolism is energy releasing process.",
        "Catabolism is a constructive while anabolism is destructive reaction."
      ],
      correctAnswerIndex: 2,
      explanation: "Anabolism is endergonic (biosynthetic, consumes ATP), whereas catabolism is exergonic (breakdown of complex molecules releasing energy)."
    },
    {
      id: "bio16-91",
      question: "A transgenic organism is an organism that:",
      options: [
        "replicates its DNA without control.",
        "can undergo chromosomal non-disjunction.",
        "has received genetic material of another organism.",
        "is artificially cultured and harvested."
      ],
      correctAnswerIndex: 2,
      explanation: "A transgenic organism (GMO) contains recombinant DNA artificially inserted from another unrelated species into its genome."
    },
    {
      id: "bio16-92",
      question: "Which of the following explains how biology takes part in biosensor technology? Using microorganism to:",
      options: [
        "monitor pollutants",
        "develop vaccines",
        "extract metals from ores",
        "produce antibiotics"
      ],
      correctAnswerIndex: 0,
      explanation: "Microbial biosensors use immobilized biological agents to detect, quantify, and monitor environmental pollutants and toxins."
    },
    {
      id: "bio16-93",
      question: "In a textile industry, microorganism's commercial products play a significant role in removing stains like grease by changing:",
      options: [
        "the acidic or basic nature of the stain molecules.",
        "the temperature of insoluble large stain molecules.",
        "the color of stain molecules to another color.",
        "large insoluble stain molecules into small and soluble ones."
      ],
      correctAnswerIndex: 3,
      explanation: "Microbial enzymes (lipases and proteases) hydrolyze large insoluble grease and protein molecules into small, soluble fragments that wash away easily."
    },
    {
      id: "bio16-94",
      question: "Which one of the following statements is correct about application of bio-pesticide in agriculture? It:",
      options: [
        "uses bacteria and fungi or their metabolites to kill insects.",
        "breakdowns glyphosate by an enzyme introduced into plant cell culture.",
        "produces insect resistant crops through modification of the plant genes using bacterial plasmids.",
        "produces toxic chemicals by crops through modification of their genes."
      ],
      correctAnswerIndex: 0,
      explanation: "Biopesticides utilize biological agents (e.g. Bacillus thuringiensis bacteria, entomopathogenic fungi) or their biochemical toxins to control pest populations."
    },
    {
      id: "bio16-95",
      question: "Which one of the following statements correctly describes bacteria? They are:",
      options: [
        "multicellular eukaryotic organisms.",
        "single celled prokaryotic organisms.",
        "single celled eukaryotic organisms.",
        "multicellular prokaryotic organisms."
      ],
      correctAnswerIndex: 1,
      explanation: "Bacteria are unicellular prokaryotic microorganisms characterized by the absence of a membrane-enclosed nucleus."
    },
    {
      id: "bio16-96",
      question: "Which one among the following processes occurs during the light independent phase of photosynthesis?",
      options: [
        "Cyclic photophosphorylation of ADP in the thylakoid",
        "Excitation of electrons from chlorophyll molecules",
        "Splitting of water molecules into its components",
        "Reduction of triose molecules by hydrogen from NADPH"
      ],
      correctAnswerIndex: 3,
      explanation: "In the Calvin cycle (stroma), 3-phosphoglycerate (PGA) is reduced to glyceraldehyde-3-phosphate (G3P / triose phosphate) using NADPH and ATP."
    },
    {
      id: "bio16-97",
      question: "As compared to non-cyclic photophosphorylation, the cyclic photophosphorylation uses:",
      options: [
        "photosystem I as the last electron acceptor.",
        "photosystem I to produce ATP and reduced NADP in the stroma.",
        "hydrolysis of water to replace electrons lost from photosystem II.",
        "photosystem II as the first electron donor to NADP."
      ],
      correctAnswerIndex: 0,
      explanation: "In cyclic photophosphorylation, electrons excited from Photosystem I (P700) pass through the electron transport chain and cycle directly back to Photosystem I without producing NADPH."
    },
    {
      id: "bio16-98",
      question: "Which one of the following chemical reactions summarizes the process of photosynthesis?",
      options: [
        "C5H10O5 + 6O2 -> 6CO2 + 12O2 + 12H2O",
        "6CO2 + 6H2O -> C6H12O6 + 6O2 + ATP",
        "C6H12O6 + 6O2 -> 6CO2 + 6H2O + ATP",
        "6CO2 + 12H2O -> C6H12O6 + 6O2 + 6H2O"
      ],
      correctAnswerIndex: 3,
      explanation: "The complete biochemical stoichiometric equation of oxygenic photosynthesis is: 6CO2 + 12H2O + Light -> C6H12O6 + 6O2 + 6H2O."
    },
    {
      id: "bio16-99",
      question: "Which one of the following statements properly describes the structure of ATP? It is made up of:",
      options: [
        "one adenine base attached to a pentose sugar and three phosphate groups.",
        "two adenine bases attached to a hexose sugar and three phosphate groups.",
        "two adenine bases attached to a deoxyribose sugar and two phosphate groups.",
        "one adenine base attached to a ribose sugar and two phosphate groups."
      ],
      correctAnswerIndex: 0,
      explanation: "Adenosine triphosphate (ATP) consists of an adenine nitrogenous base bonded to a 5-carbon ribose pentose sugar and three ester-linked phosphate groups."
    },
    {
      id: "bio16-100",
      question: "Which one of the following descriptions about glycolysis is correct? It is a process:",
      options: [
        "of producing acetyl CoA from pyruvate by releasing CO2.",
        "that produces a net of 4 ATP through substrate level phosphorylation.",
        "of breaking down of a glucose molecule to two pyruvates.",
        "that takes place in the cytosol with high demand of oxygen."
      ],
      correctAnswerIndex: 2,
      explanation: "Glycolysis is the anaerobic enzymatic breakdown of a 6-carbon glucose molecule into two 3-carbon pyruvate molecules, yielding a net 2 ATP and 2 NADH."
    }
  ]
};
